version: '3'
services:
    metabase:
        container_name: "data-engine_metabase"
        restart: "always"
        image: metabase/metabase
        env_file:
            - ./metabase_config/metabase_database.env
        volumes:
            - ./metabase-data:/metabase-data
        ports:
            - "3000:3000"
